version: '3.8'

volumes:
  postgresql-volume:

services:
  postgres_db:
    image: "postgres"
    container_name: "postgres_db"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
